services:
  - type: web
<<<<<<< HEAD
    name: yellowroam-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn prototype.app:app
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
=======
    name: yellowroam
    env: python
    autoDeploy: true
    region: oregon
    build:
      cwd: prototype
    start:
      cwd: prototype
    buildCommand: pip install -r requirements.txt   # â† just this!
    startCommand: gunicorn app:app
>>>>>>> fb568a5 (Initial commit with Flask app and config setup)
